baseURL = 'https://github.com/huz4f/huz4f.git'
title = 'Huzaif'
theme= "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

#googleAnalytics = "UA-123-45"

[minify]
  disableXML = true
  minifyOutput = true

[params]
  env = "production" # to enable google analytics, opengraph, twitter-cards, and schema.
  title = "Huzaif"
  description = "was bored created a website, now i write "
  keywords = ["Blog", "Computer Science", "Life"]
  author = "Huzaif"
  # author = ["Me", "You"] # multiple authors
  #images = [""]
  DateFormat = "January 2, 2006"
  defaultTheme = "auto" # dark, light
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = false
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

  [params.label]
    text = "< ð–ð–š/>"
    icon = ""
    iconHeight = 69

  [params.assets]
    favicon = "/favicons/favicon.ico"
    favicon16x16 = "/favicons/favicon-16x16.png"
    favicon32x32 = "/favicons/favicon-32x32.png"
    apple_touch_icon = "/favicons/apple-touch-icon.png"
    safari_pinned_tab = "/favicons/safari-pinned-tab.svg"

  [params.profileMode]
    enabled = true # needs to be explicitly set
    subtitle = "i am **Huzaif** Shabir "
    title = "Welcome! \U0001F44B"
    imageUrl = "https://lh3.googleusercontent.com/pw/AP1GczN3qRTC-CIY8DjTbkh8tXI2MAQiykqgluUJTZPMnjC-ZhJ65la3i9BHzMrw5UNM1TJ88ooQ5dMBdMwmSIc_ssO6Tr2MPo2tyBT1TXLd0Ft4qa_FSs1MYcJAqo7tOF-bB6bDkxnLx89CkUjbVX2zIgdDhCuHeuMiFTRBjwR37BndQWfSSA92VPENcJQOF3SAx8u5K8gLzDd2EspcmThRD62JChwc_Rcjo4cPNrgDg90WuvhTD7dFaTreEdeLLYDUeUFYndquTTIbgG09pzkVbPOTwiUCGiFdLTo-BPiTHVX9-c4uyqFp6oxj2LiXBf6vdvXWdLx-4bPCvJikN5o3x5mOS7HUCv2lF4Zh6nlgrH9wtK4nrHxT3VlvH9TdjpxsU2W5VX48dIb4aB8ZI6wdrSZe2VPVn3TBFHrlSmKJinxk4JEfaTg_7DZ_l7KbV_w7VS0a-VPYoLmz-dMUeiTzCUNWRsvndA9cg1KQ6EaOfs3NEnEMVCv_4ghMgJidGvf9_opSeNY4G1X_Z6m3-thy6BJ-lQjPn8efIa_NjlnoCi_3w7HSe4nZrP1QqYI8X-GRwYguMW_pqh4al6PXOuGChA8U_1eDuANuE6u50IUWxLEgdodvfry3COsmBv2stoIEmjzuU6sqwKeG1H-R0u12h_146J1Z_2RitTfzct-PDjuH9cyOlgYrWm7ZJgqBpW3Nolnx_M0agBIl96q4gEOmYFWjkqVXKtLReSW1fWKw7gmLn8tB_KAHpkkdxJeDFNFo0B-K2EHGsYaMvJXZAdtBMl25YuSDBkKtXDc3O_je-jxctaaFVFVF9Cgyd1GUCZ4oLcwX0XL1ColIz038idZSn4_k1a73m0DdmV9DYq1C4l3dUP3irx_hJ5x5wmTlOzn9JXdhqlNPcpK06gc0igOCNyMW0IM=w945-h944-s-no?authuser=0"
    imageWidth = 140
    imageHeight = 140
    imageTitle = "Huzaif"

    [[params.profileMode.buttons]]
      identifier = "tags"
      name = "Explore"
      url = "/tags/"

  #[params.homeInfoParams]
    #Title = ""
    #Content = ""

  #[[params.socialIcons]]
    #name = "youtube"
    #url = "http://youtube.com/huz4f"

  #[[params.socialIcons]]
    #name = "medium"
    #url = ""

  #[[params.socialIcons]]
    #name = "x"
    #url = "https://twitter.com/hu_z4f"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/huz4f/"

  [[params.socialIcons]]
    name = "CV"
    url = ""

  [[params.socialIcons]]
    name = "Github"
    url = "https://github.com/huz4f"

  #[[params.socialIcons]]
    #name = "discord"
    #url = "https://discordapp.com/users/huz4f/"

  #[[params.socialIcons]]
    #name = "phone"
    #url = "https://Vsco.co/huz4f"
  


  [params.analytics.google]
    SiteVerificationTag = ""

  [params.analytics.bing]
    SiteVerificationTag = ""

  [params.analytics.yandex]
    SiteVerificationTag = ""

  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = ["title", "permalink", "summary", "content"]

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 5

[[menu.main]]
  identifier = "Blogs"
  name = "Blogs"
  url = "/blogs/"
  weight = 4

[[menu.main]]
  identifier = "Tech"
  name = "Tech"
  url = "/Articles/"
  weight = 1

#[[menu.main]]
  #identifier = "wiki"
  #name = "wiki"
  #url = "/wiki/"
  #weight = 3

[[menu.main]]
  identifier = "Projects"
  name = "Projects"
  url = "/Projects/"
  weight = 2

